// This file is generated by Slice Machine. Update with care!

import Features from './Features';
import Hero from './Hero';

export {
	Features,
	Hero,
};

export const components = {
	features: Features,
	hero: Hero,
};
